### PR TITLE
394 bug mobile question page bugs

### LINKED ISSUE #394: bug: mobile question page bugs
### Describe the bug

- "answering questions and cycling between questions in an assignment on mobile only works sometimes"
- "the hitbox for selecting answers on mobile is really tiny, u can only select if u hit the very right edge of each answer choice"

### Expected behavior

good luck

### Steps to reproduce

have fun

### Additional information

_No response_

### Validations

- [x] Check that there isn't [already an issue](https://github.com/sitechtimes/regents-prep-app-frontend/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this isn't a you problem. Ensure you are up to date with `dev` and you have `npm install`ed everything you need to.

### PR DESCRIPTION
**Pull request by rylan-geykhman**
### Changes

- now on phone you can actually click buttons
- Due to @BSelyomin's expert oversight, the hover effects are now a slightly different shade of grey.
- "relative z-40" is the solution to all problems

### CODE REVIEW

**Review by kennething — APPROVED** [review]
image

File: components/student/Assignment/DynamicQuestion.vue [hunk 1]
```diff
@@ -10,9 +10,9 @@
       <div v-if="currentQuestion?.question.answerType === 'Multiple Choice'" v-for="choice in currentQuestion?.question.answers" class="mt-4 flex w-full flex-col items-start space-y-3">
         <button
           type="button"
-          class="w-full rounded-lg bg-neutral-200 px-6 py-3 text-left shadow-sm hover:bg-neutral-500/50 dark:bg-neutral-500/25 dark:hover:bg-neutral-500/50"
+          class="w-full rounded-lg bg-neutral-200 px-6 py-3 text-left shadow-sm hover:bg-neutral-400/50 dark:bg-neutral-500/25 dark:hover:bg-neutral-500/50"
```
Comment (bridgetf7) [inline components/student/Assignment/DynamicQuestion.vue:13]: https://github.com/sitechtimes/regents-prep-app-frontend/wiki/Design-Language#light-mode

use this wiki to reference hover colours

**Review by bridgetf7 — CHANGES_REQUESTED** [review]

**Review by bridgetf7 — APPROVED** [review]

File: components/student/Assignment/DynamicQuestion.vue (hunk 1 above)
Comment (kennething) [reply components/student/Assignment/DynamicQuestion.vue:13]: nah id win
