### PR TITLE
312 bug student dashboard class component missing proper color theme when the student joins a class

### LINKED ISSUE #312: bug: Student dashboard class component missing proper color 'theme' when the student joins a class
### Describe the bug

When a student joins any class, the class that appears in the student dashboard is missing the proper theme. As a result, the component appears either entirely blank or dark depending on the application's current theme setting (light or dark mode).

### Expected behavior

When a studnet joins a class, that new class component that appears in their dashboard should keep their theme, rather than turning blank.

### Steps to reproduce

1. Log into a student account
2. Access the student dashboard
3. Join a class that student has not currently joined

### Additional information

Split from #310 

### Validations

- [x] Check that there isn't [already an issue](https://github.com/sitechtimes/regents-prep-app-frontend/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this isn't a you problem. Ensure you are up to date with `dev` and you have `npm install`ed everything you need to.

### PR DESCRIPTION
**Pull request by katiekhamarkhanova**
- When user first joined class, there was no color background on dashboard card and it only appeared after refreshing. I made the page reload right after a user enrolls in a new class, so the color background appears.

### CODE REVIEW

File: components/student/Dashboard/DashboardCard.vue [hunk 1]
```diff
@@ -1,51 +1,54 @@
...
-    :to="`/student/course/${course.id}`"
-    class="hover:border-border-neutral-500 flex w-115 flex-col items-center justify-center overflow-hidden rounded-xl border border-neutral-300 bg-body transition hover:shadow-lg dark:border-neutral-600"
-    type="button"
-  >
-    <div class="flex h-24 w-full flex-col items-center justify-end p-2" :style="{ backgroundColor: subjectColors[course.subject] }">
-      <h2 :title="course.name" class="w-72 overflow-hidden overflow-ellipsis text-nowrap text-center text-2xl font-semibold">{{ course.name }}</h2>
-      <p class="text-sm">Period {{ course.period }}</p>
-      <p>{{ course.teacher }}</p>
-    </div>
+  <div :key="refreshKey">
```
Comment (kennething) [inline components/student/Dashboard/DashboardCard.vue]: what does this do

File: components/student/Dashboard/DashboardCard.vue [hunk 2]
```diff
@@ -1,51 +1,54 @@
...
+        <p v-else>No assignments</p>
+      </div>
+    </NuxtLink>
+  </div>
 </template>
 
 <script setup lang="ts">
 const props = defineProps<{ course: StudentCourse }>();
-
+const studentCourses = storeToRefs(useUserStore()).studentCourses;
```
Comment (kennething) [inline components/student/Dashboard/DashboardCard.vue]: use destructuring for storetorefs and define useuserstore as a variable above instead

File: components/student/Dashboard/DashboardCard.vue [hunk 3]
```diff
@@ -1,51 +1,54 @@
...
-  >
-    <div class="flex h-24 w-full flex-col items-center justify-end p-2" :style="{ backgroundColor: subjectColors[course.subject] }">
-      <h2 :title="course.name" class="w-72 overflow-hidden overflow-ellipsis text-nowrap text-center text-2xl font-semibold">{{ course.name }}</h2>
-      <p class="text-sm">Period {{ course.period }}</p>
-      <p>{{ course.teacher }}</p>
-    </div>
+  <div :key="refreshKey">
+    <NuxtLink
+      :to="`/student/course/${course.id}`"
+      class="hover:border-border-neutral-500 flex w-115 flex-col items-center justify-center overflow-hidden rounded-xl border border-neutral-300 bg-body transition hover:shadow-lg dark:border-neutral-600"
```
Comment (kennething) [inline components/student/Dashboard/DashboardCard.vue]: what is border-border

File: components/student/Dashboard/DashboardCard.vue [hunk 4]
```diff
@@ -1,51 +1,54 @@
...
+      </div>
+    </NuxtLink>
+  </div>
 </template>
 
 <script setup lang="ts">
 const props = defineProps<{ course: StudentCourse }>();
-
+const studentCourses = storeToRefs(useUserStore()).studentCourses;
+const refreshKey = ref(0);
```
Comment (kennething) [inline components/student/Dashboard/DashboardCard.vue]: why do we need to refresh the page when they join a class

File: components/student/Dashboard/JoinClass.vue [hunk 5]
```diff
@@ -61,17 +60,20 @@ async function submit() {
   if (!joinCode.value) return;
   isLoading.value = true;
   isErrored.value = false;
-
   try {
     const course = await joinCourse(joinCode.value);
     isLoading.value = false;
-
-    studentCourses.value.splice(0, 0, course);
+    userStore.$patch((state) => {
```
Comment (kennething) [inline components/student/Dashboard/JoinClass.vue]: ??? what is this for

File: components/student/Dashboard/JoinClass.vue [hunk 6]
```diff
@@ -61,17 +60,20 @@ async function submit() {
...
+      state.studentCourses = [...state.studentCourses, course];
+    });
     isSuccess.value = true;
 
     setTimeout(() => {
       isSuccess.value = false;
       closeModal();
+      setTimeout(() => {
```
Comment (kennething) [inline components/student/Dashboard/JoinClass.vue]: why do we need to reload when we join a class

File: utils/courses.ts [hunk 7]
```diff
@@ -1,9 +1,9 @@
-export const subjectColors = {
+export const subjectColors = reactive({
```
Comment (kennething) [inline utils/courses.ts]: what is this reactive for?

**Review by kennething — CHANGES_REQUESTED** [review]

File: components/student/Dashboard/JoinClass.vue (hunk 6 above)
Comment (katiekhamarkhanova) [reply components/student/Dashboard/JoinClass.vue]: the color background only appears after reloading

Comment (kennething) [reply components/student/Dashboard/JoinClass.vue]: find the reason why it only appears after reloading and try to fix that

File: components/student/Dashboard/JoinClass.vue [hunk 8]
```diff
@@ -61,7 +61,6 @@ async function submit() {
   if (!joinCode.value) return;
   isLoading.value = true;
   isErrored.value = false;
-
```
Comment (kennething) [inline components/student/Dashboard/JoinClass.vue]: y remove this newline

**Review by kennething — CHANGES_REQUESTED** [review]

**Review by bridgetf7 — APPROVED** [review]

**Review by kennething — APPROVED** [review]
LGTM
this was a backend problem
