### PR TITLE
353 bug student stats

### LINKED ISSUE #353: bug: student stats
### Describe the bug

1. fails to get assignment date for some assignments (frick those assignments in particular)
2. error when looking at static assignments (figure it out)

### Expected behavior

yes

### Steps to reproduce

yes

### Additional information

yes

### Validations

- [x] Check that there isn't [already an issue](https://github.com/sitechtimes/regents-prep-app-frontend/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this isn't a you problem. Ensure you are up to date with `dev` and you have `npm install`ed everything you need to.

### PR DESCRIPTION
**Pull request by rylan-geykhman**
### Changes

- Static assignments now actually have stats (woah)
- Dynamic assignments and static assignments both show submitted dates.

### CODE REVIEW

File: pages/student/course/[courseCode]/[assignmentId]/stats.vue [hunk 1]
```diff
@@ -39,12 +39,26 @@
           <div class="flex-1 px-4">
             <span class="overflow-hidden text-ellipsis" v-html="questionInstance.question.text"></span>
           </div>
-          <div class="w-1/4 text-center">
-            <span v-html="getUserAnswer(questionInstance.question, questionInstance.dynamicUserAnswers.map(String))"></span>
+          <div v-if="questionInstance.dynamicUserAnswers" class="w-1/4 text-center">
+            <span v-html="getUserAnswer(questionInstance.question, questionInstance.dynamicUserAnswers?.map(String) || [])"></span>
```
Comment (kennething) [inline pages/student/course/[courseCode]/[assignmentId]/stats.vue]: use `??` instead of `||`

File: pages/student/course/[courseCode]/[assignmentId]/stats.vue [hunk 2]
```diff
@@ -39,12 +39,26 @@
...
+          </div>
+          <div v-else-if="questionInstance.staticUserAnswer" class="w-1/4 text-center">
+            <span v-html="getStaticUserAnswer(questionInstance.question, Number(questionInstance.staticUserAnswer) || 0)"></span>
```
Comment (kennething) [inline pages/student/course/[courseCode]/[assignmentId]/stats.vue]: .

**Review by kennething — CHANGES_REQUESTED** [review]
change `isAnswerCorrect` to `isDynamicAnswerCorrect`

File: pages/student/course/[courseCode]/[assignmentId]/stats.vue [hunk 3]
```diff
@@ -77,20 +91,14 @@ const route = useRoute();
...
-const currentAssignment = ref<StudentAssignment>();
 const dropdownStates = ref<boolean[]>([]);
+const assignmentId = Number(route.params.assignmentId);
+const currentAssignment = computed(() => studentCurrentCourse.value?.assignments.find((assignment) => assignment.id === assignmentId));
 
 onMounted(async () => {
   const courseId = studentCurrentCourse.value?.id;
   if (!courseId) return;
 
-  const assignmentId = parseInt(route.params.assignmentId as string);
```
Comment (kennething) [inline pages/student/course/[courseCode]/[assignmentId]/stats.vue:88]: good job for deleting useless code

**Review by kennething — APPROVED** [review]
LGTM probably

File: pages/student/course/[courseCode]/[assignmentId]/stats.vue (hunk 3 above)
Comment (rylan-geykhman) [reply pages/student/course/[courseCode]/[assignmentId]/stats.vue:88]: there was new code too :(

**Comment by bridgetf7** [comment]
fantastic

**Review by bridgetf7 — APPROVED** [review]
