### PR TITLE
381 bug password reset not displaying proper error

### LINKED ISSUE #381: bug: Password reset not displaying proper error
### Describe the bug

When the user resets their password, they are not given clear direction as to why their password reset failed: the same statement on the frontend is returned whether password1 and 2 mismatch or if they are simply invalid.

### Expected behavior

When the user resets their password, they should be given an indication as to why their password reset failed- for example, "passwords do not match" if password1 and password2 do not match.

### Steps to reproduce

1) Reset Password for an account
2) Enter an invalid password / passwords that do not match

### Additional information

Please be sure to account for the error format that is returned from the backend- whether it is an object or an array inside of an object.

### Validations

- [x] Check that there isn't [already an issue](https://github.com/sitechtimes/regents-prep-app-frontend/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this isn't a you problem. Ensure you are up to date with `dev` and you have `npm install`ed everything you need to.

### PR DESCRIPTION
**Pull request by gliberov**
### Changes

- implemented password error popup
- WARNING: should not work due to camelCase inputs not being implemented yet in the backend
-

### CODE REVIEW

File: pages/reset-password/confirm.vue [hunk 1]
```diff
@@ -50,12 +50,13 @@ const submitError = ref(false);
 const showModal = ref(false);
 const route = useRoute();
 const router = useRouter();
-
+const errorMessage = ref("");
```
Comment (kennething) [inline pages/reset-password/confirm.vue:70]: r u allergic to newlines
use empty lines to group refs and stuff by topic, dont stack them all on top of each other this isnt tetris

example groupings
not a science just group by vibe
```ts
// route stuff
const route = useRoute();
const router = useRouter();

// query stuff
const uid = String(route.query.uid ?? "");
const token = String(route.query.token ?? "");

// input stuff
const newPassword1 = ref("");
const newPassword2 = ref("");

// submitting stuff
const loading = ref(false);
const errorMessage = ref("");
const notMatching = ref(false);
const submitError = ref(false);

// misc
const showModal = ref(false);
```

File: pages/reset-password/confirm.vue [hunk 2]
```diff
@@ -64,17 +65,21 @@ async function onSubmit() {
...
-  if (error) {
-    console.error("Password reset failed:", error);
+  if (typeof response === "string") {
+    errorMessage.value = response;
+    if (response.includes("Password has been reset with the new password.")) {
+      showModal.value = true;
+    } else {
+      submitError.value = true;
+    }
+  } else {
```
Comment (kennething) [inline pages/reset-password/confirm.vue]: make this a guard clause

File: pages/reset-password/confirm.vue [hunk 3]
```diff
@@ -64,17 +65,21 @@ async function onSubmit() {
...
-  const { error } = await tryCatch(confirmResetPassword(uid, token, newPassword1.value, newPassword2.value));
-
-  loading.value = false;
+  const { data: response } = await tryCatch(confirmResetPassword(uid, token, newPassword1.value, newPassword2.value));
 
-  if (error) {
-    console.error("Password reset failed:", error);
+  if (typeof response === "string") {
+    errorMessage.value = response;
+    if (response.includes("Password has been reset with the new password.")) {
```
Comment (kennething) [inline pages/reset-password/confirm.vue]: does this need to be includes or can it just be ===
also make it a 1 liner

File: pages/reset-password/confirm.vue [hunk 4]
```diff
@@ -64,17 +65,21 @@ async function onSubmit() {
...
+      showModal.value = true;
+    } else {
```
Comment (kennething) [inline pages/reset-password/confirm.vue]: 1 liner

File: utils/fetch.ts [hunk 5]
```diff
@@ -227,10 +230,34 @@ export async function resetPassword(email: string) {
...
+      },
+      true
+    )
+  );
+
+  if (error) return console.error(error);
+
+  if (data) {
+    if (data.newPassword2) {
+      const returnData = data.newPassword2[0];
```
Comment (kennething) [inline utils/fetch.ts]: just return `data.newPassword2[0]` ur not using the variable for anything else
also 1 liner the if statement

File: utils/fetch.ts [hunk 6]
```diff
@@ -227,10 +230,34 @@ export async function resetPassword(email: string) {
...
+      return returnData;
+    }
+    if (data.detail) {
```
Comment (kennething) [inline utils/fetch.ts]: ^

File: utils/fetch.ts [hunk 7]
```diff
@@ -227,10 +230,34 @@ export async function resetPassword(email: string) {
...
+      const returnData = data.detail;
+      return returnData;
+    }
+    if (data.token) {
```
Comment (kennething) [inline utils/fetch.ts]: ^

File: utils/fetch.ts [hunk 8]
```diff
@@ -227,10 +230,34 @@ export async function resetPassword(email: string) {
...
+        newPassword1,
+        newPassword2
+      },
+      true
+    )
+  );
+
+  if (error) return console.error(error);
+
+  if (data) {
```
Comment (kennething) [inline utils/fetch.ts]: i think this if is unnecessary

**Review by kennething — CHANGES_REQUESTED** [review]
delete PasswordResetModal and implement FullScreenModal instead

**Review by kennething — DISMISSED** [review]
