### PR TITLE
277 feature teacher createclass modal

### LINKED ISSUE #277: feature: teacher createClass modal
### Description

Add an actual modal for success/fail in the `teacher/createClass` component instead of using `alert`.
The modal should handle both success and fail of the `submitCreateCourse` request.

### Suggested solution

The modal can either be small and above the submit button, or a full-screen modal.
You could use Vue's <Transition> block to make transitions or wtv if you choose to make a full-screen modal.
Just make sure it looks good 😊

### Rationale

Alerts should not be used for modals + it would look better

### Validations

- [x] Check that there isn't [already an issue](https://github.com/sitechtimes/regents-prep-app-frontend/issues) that suggests the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by AbigailLabanok**
Additions:
- added a modal to indicate a teacher successfully creating a new course 

Removals:
- removed the alert that was used to do this prior

### CODE REVIEW

**Review by kennething — CHANGES_REQUESTED** [review]
can you rename mymodal1 to something more descriptive

File: components/teacher/CreateClass.vue [hunk 1]
```diff
@@ -35,19 +35,33 @@
...
             type="submit"
+            @click="createdCourseModal?.showModal()"
           >
             Create
           </button>
         </div>
       </div>
     </div>
   </Transition>
+  <dialog ref="createdCourseModal" class="modal rounded-lg p-6">
```
Comment (kennething) [inline components/teacher/CreateClass.vue]: daisyui classes have a `du-` prefix, are you forgetting something

File: components/teacher/CreateClass.vue [hunk 2]
```diff
@@ -35,19 +35,33 @@
...
+    <div class="modal-box">
```
Comment (kennething) [inline components/teacher/CreateClass.vue]: ^

File: components/teacher/CreateClass.vue [hunk 3]
```diff
@@ -35,19 +35,33 @@
...
+      <h3 class="text-lg font-bold">Congrats!</h3>
+      <p class="py-4">You have successfully created a course!</p>
+      <div class="modal-action">
```
Comment (kennething) [inline components/teacher/CreateClass.vue]: ^

File: components/teacher/CreateClass.vue [hunk 4]
```diff
@@ -35,19 +35,33 @@
...
+        <form method="dialog">
```
Comment (DubNubz) [inline components/teacher/CreateClass.vue:51]: ^

File: components/teacher/CreateClass.vue [hunk 5]
```diff
@@ -35,19 +35,33 @@
             :disabled="!courseName || !courseSubject || !coursePeriod"
             form="create-course"
             type="submit"
+            @click="createdCourseModal?.showModal()"
```
Comment (kennething) [inline components/teacher/CreateClass.vue]: should be in the submit function instead of the button since everything about this form happens in the submit function and not the button

**Review by kennething — CHANGES_REQUESTED** [review]

**Review by kennething — APPROVED** [review]
LGTM
