### PR TITLE
282 bug hassle with re logging in after login failure

### LINKED ISSUE #282: bug: hassle with re-logging in after login failure
### Describe the bug

If you try to login with a valid email but invalid password (or vice versa), you will need to change both fields before `loginWithEmail` can be called again.

This is due to the guard clause at the top of the function, where if an email OR password error exist, an early return will be triggered.

### Expected behavior

`loginWithEmail` should be able to be called if either email OR password is changed after a login error, not email AND password.

### Steps to reproduce

Try to log in with a valid email but invalid password, or vice versa

### Additional information

Remove `name`, `nameErr`, and anything associated with them. They are unused.

### Validations

- [x] Check that there isn't [already an issue](https://github.com/sitechtimes/regents-prep-app-frontend/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this isn't a you problem. Ensure you are up to date with `dev` and you have `npm install`ed everything you need to.

### PR DESCRIPTION
**Pull request by AbigailLabanok**
### Changes

- fixed bug where you had to change both email and password after getting an incorrect login attempt (#282)
- added loginErr constant --> checks for non_field_errors during login attempt

### CODE REVIEW

**Review by kennething — CHANGES_REQUESTED** [review]
fix your eslint errors and remove everything to do with passwordErr too, i dont think we need it

File: pages/login.vue [hunk 1]
```diff
@@ -31,10 +31,14 @@
           <p v-show="passwordErr.length > 0" class="error absolute font-medium text-red-500">{{ passwordErr }}</p>
         </div>
 
-        <button class="rounded-lg bg-green-accent px-16 py-2 hover:brightness-[0.85]" type="submit">
-          <span v-if="loading" class="loading du-loading du-loading-sm"></span>
-          <p v-else class="text-lg">Login</p>
-        </button>
+        <p v-show="generalErr.length > 0" class="error my-[-1rem] font-medium text-red-500">{{ generalErr }}</p>
```
Comment (kennething) [inline pages/login.vue]: use `-my-4` instead

File: pages/login.vue [hunk 2]
```diff
@@ -49,52 +53,48 @@ useSeoMeta({
...
 async function loginWithEmail() {
-  if (emailErr.value || passwordErr.value || nameErr.value) return;
+  if (emailErr.value || passwordErr.value || generalErr.value) return;
   loading.value = true;
   const data = await userStore.login(email.value, password.value);
   if (!data) {
     void router.push(`${userStore.userType}/dashboard`);
   } else {
-    if ("non_field_errors" in data) emailErr.value = data.non_field_errors.join(" ");
+    if ("non_field_errors" in data) generalErr.value = data.non_field_errors.join(" "); //why only for email?
```
Comment (kennething) [inline pages/login.vue]: remove comment

**Review by kennething — CHANGES_REQUESTED** [review]

**Review by kennething — APPROVED** [review]
LGTM
